### DISCUSSION TITLE
How to Cucumber Runner (Serenity/JS, Cucumber, Playwright) Parallel Execution and Serenity BDD Report Generation

### DISCUSSION THREAD

**Discussion by dev-wahyuinc** [serenity-js/serenity-js#2833] [How to... ?]
I am currently using Serenity/JS with Cucumber and Playwright, and I have configured parallel execution in my cucumber.yaml file as follows:

YAML

``` yaml
default:
  requireModule:
    - ts-node/register
  format:
    # - 'html:cucumber-report.html'
    - '@serenity-js/cucumber' # attach Serenity/JS Cucumber adapter
  require:
    - './features/**/*.steps.ts' # load step definition libraries
    - './features/**/*.config.ts' # load configuration files
  parallel: 2
  filter:
    - tags: 'not @manual' # exclude scenarios tagged with @wip
  retryTagFilter: '@flaky' # only retry scenarios tagged with @retry
  retry: 1 # retry failed scenarios once
```

When I run my tests, they do execute in parallel. However, the Serenity BDD report does not contain any data. I am wondering if there is an issue with my configuration that is preventing the Serenity BDD report from being generated correctly in parallel execution mode. Am I missing something or is there an error in my cucumber.yaml configuration that is causing this?"
